### ISSUE TITLE
AssertionError [ERR_ASSERTION]: Task function must be specified 

### ISSUE THREAD

**Issue by sailajaVelampati** [danielstern/integration-test-repo-demo#5]
I am following your course in pluralsite and stuck with this error . 
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (D:\CICD-node\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (D:\CICD-node\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (D:\CICD-node\gulpfile.js:6:6)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at requireOrImport (C:\Users\m1048573\AppData\Roaming\npm\node_modules\gulp\node_modules\gulp-cli\lib\shared\require-or-import.js:19:11) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}

**Comment by danielstern** [comment]
Probably a Gulp versioning issue.

I'd say roll back to the version of Gulp referenced in package.json

Good luck
________________________________
